/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentFloat: typeof import('./components/AgentFloat/index.vue')['default']
    AppBreadcrumb: typeof import('./components/AppBreadcrumb/index.vue')['default']
    AppTabs: typeof import('./components/AppTabs/index.vue')['default']
    BaseButton: typeof import('./components/ui/BaseButton/index.vue')['default']
    BaseCard: typeof import('./components/ui/BaseCard/index.vue')['default']
    BaseModal: typeof import('./components/ui/BaseModal/index.vue')['default']
    CaseCard: typeof import('./components/CaseCard/index.vue')['default']
    CaseDetailSkeleton: typeof import('./components/shared/CaseDetailSkeleton/index.vue')['default']
    CaseStatusHero: typeof import('./components/CaseStatusHero/index.vue')['default']
    CurrentTaskCard: typeof import('./components/CurrentTaskCard/index.vue')['default']
    DocumentCard: typeof import('./components/DocumentCard/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./components/shared/ErrorBoundary/index.vue')['default']
    EvidenceCard: typeof import('./components/EvidenceCard/index.vue')['default']
    FileUploader: typeof import('./components/FileUploader/index.vue')['default']
    FormGuide: typeof import('./components/FormGuide/index.vue')['default']
    InlineHint: typeof import('./components/InlineHint/index.vue')['default']
    NotifyBell: typeof import('./components/NotifyBell/index.vue')['default']
    NotifyPopover: typeof import('./components/NotifyPopover/index.vue')['default']
    PermissionButton: typeof import('./components/PermissionButton/index.vue')['default']
    ProcessTimeline: typeof import('./components/ProcessTimeline/index.vue')['default']
    QuickActionGrid: typeof import('./components/QuickActionGrid/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepIndicator: typeof import('./components/StepIndicator/index.vue')['default']
    StepWizard: typeof import('./components/business/StepWizard/index.vue')['default']
    Timeline: typeof import('./components/business/Timeline/index.vue')['default']
    TimelineLog: typeof import('./components/TimelineLog/index.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar/index.vue')['default']
  }
}
